sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester@^5.0.0
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: UGvFgVLVCaXmNouQz/mHWbYeVpqmEiIa5gTRZWDtS0hNHWUdPmUJoR4Lzn9DJLu7eZTmLo1dO4TXq16WCGnmrLvkjA9r1cRoh2WaG/O8FTR9GLK8RtIXRiNyP43WM6PmUIETeGl2YxSy2yKjmt21CU1dn5q1CWo/UkBOHgNFEIEFDlKAGp5mB3PbmkV77SlnLIz0gM1OKc25JShtHFgIday5oQMtWVTnyn28OeO4Psk7L7zHD43LQz17Q3hCRYmKZ+UmayTrVy4HS9fUdcq+k8hR19XuX6cLSvzuw9QyIT/IdOJpYjdhVNckKy9r2REDFn3ylwB2R4qD3FDmqoQ7aLGrGeXKWm65J3FhNaraHFvgZugT0WTQOC3IqviFKfqKsLg5HVyPh0Zq3um1CbLGXYVImP8A5Bg1587+oHKrcF9i+jKPJr81EqULNCveJ6yJTQrbqxsuwGc1zY0QvGcnaHgOycuSpvK75BOnBulXWemnPds75xc+0y5wcn3pflFG+NnHZBYhQ+VW6HsA1/aMKo12vvXQ0Daiikf0IySOoKz8z5EjQjXY1RZkJHVfOhvB1jpdzqxohqD39w+14VlOmRdy3eqC5Jz0qpW5NzE2UjQA156CzDNlqmvblBmgZVanqxNhJA1T+ZRam6f27RpVE4ekttOTJSX8DWBkXpDTqQk=
  - secure: s1xl8hYMdUygFORPuvi00AxMAtYA8q6uxB3ua6r3z35uM41vv6Wt9OxpaC2vd/WxmwfDU1VN+i5DKFfQkWI/xvlTn9MEncB2vyQVX/g9SqrN+sbSCEFLGh6hqCWCIW3ho87oEmmCpKOM5O3qIes12eCxtxRYheIiq5A2kg2I+JJ8W+XmYQHMkr+uBotvrpNJQjHFrLOPnB6gfSbR+gNQWvW7Apa370w7q+GCAQpoFq/xAzmevdC6/Ab/fFfRQrkLeP1jj9RkGr1IMXIqo+tHXUM/cU1kL3KGnkFFbeDL2VPTFKBIuS9ws5dVv+LvTLMviNCTdok55vtHitLjRJkSnk1efzqVif3UYARsPBoOJFy9fqqvtXzrBGmenbU2dQHG+bHIxxxjFdewk6Dz81utmGHQSjxcyKoKySMqzBb0gPEWL4VBQBy0QKeXiOl+QtG0YVkUKoFNHPqYkFdF62bort/uOPTsywDDX0sdR6HCl1LzJUDjapDK/O2T/1HUb9RNELoZZCB4irbybOl88Vy4K2AkSaOGFlZycizdreWQxqjGDNaOjavGw2RDWNqOYX8S2vcORzNURiXTwYkOuj5s43xej6h3Pvj17ATce8l+adBEZtazPz8daLATvKruN1ROQsaCCogXTpdAZQOjOCszT1prU9ZixlmdTBI9D+oj8ec=
  - secure: M1sKyAWkRbuxhnljZbJ/rbTdfzE/WhZqsccDmZicDjctUodVMvUEDhm5xoHL/l42sxJNoPOC11NVzZH+WzhY+WzbJqe2rEljarzrdS6DHEwBx5WxuosP9yKlGsGNBwT2ttc3TYjgMd1Ivz7rT+UqFfZ09FBFdlgO2epJLMTDh4KG1HauDPt9JUeYDxeq0TojkWrJDeESXQssU5BN8G0Ieua20LF1h2De8pcsIKZqnav99Iq0Kuz6CnYHUzgjdun95kzgCTPIP+e/8d2xc3gvcmHIOJU0pWlYbDKh2xESjnyv5Wxc8wOP0LRlVw86+avBomIYhY1Bf6+kfzDmmMA9R/n04SX0J/7A6GIzzIFiENyD0z4wxbjKjJGsNpEWuuuh/ROBnrbP1SCD/GacXG6dUvEcwwCUQ6iKgTa+98dDkasEh4hnEXwZQgAyLXXt1ib2xOPqPKo3V+qMAd0kcPQpCGP0/EXZ8g0BGPrJd87Cbck1G0Ldke58zOYZlj7nzsXgzoydurxmuk4/zyedSpTGqKFzPHSw8YmGVRplydVHQoAUUyD84a9zZwXv5YZEAF9VGrs6Nm+/dnx7e7+IpSXKbUgrGmsJ7J84ZKvfcz4Y6i/0awLEWORqEe4OkppUfXDxC/5l+0IN6EI4QskXaCh4dHFfT9PIyrq3vqlF+MQIUs0=
  - secure: Y2ZVRyM+q+sJd6fywFf/kQSe8RmIwr94v6UpMnqDTWgZHR/TArIRJw+ClqiL+Bwsa40/RlIa1pHmyszUF40oTajD5QH2PuK6OSmUOvhV+eqjZV+7MXxtIKo+v92AO6zAROSXtX99VO3k++rU/sp2+mNLoCmL9IgALMf43R+A78a53nI110XCwPft3G6dEGqpaKRotyu4FNpAl+Xa0IeVKcmB/z+pQn5y6kGS+Fwotj1WaIlgV8qj16Nfj2+Z6Rux/h/Ltq7tCZGJkuO8cQpECUbnICi3eFsoCQptvz54iarCdoFs4BvvagTK+zxDfNv+ma5/gYnQ2VPRzVsWCtOsjrCvo+hxRNcaRB8Lsu9oJMU1cNsFTob+s5U1wrUDzb+896DqPAFgZCIPKdvl/InrMVmjg9siKoxA7w3h6JOG9kKcHbCuV2JT/3RZ6qMldYVq61YXmKTaW3o0zBd7Bh4mPcMEMf3OMPoZubtX1BdYREv3bIBmFL+cxiMsgZMvRpqtQ3dbKLmiE4jhS3vXCGXfBwepgGEQSQsqt1tVwrff6ZHEnoN6STZutjsVMNSOXeGdQM/tfQMrTSEcVs8Y1feC8XGfRMsH/8o5Z/SrU50ABxzHrbynCgBjoNv1jIrBzTsHGNULSnweDQBmCp+CEHRi8dcI5d6h0nKNQ34Rf9gDDws=
